Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  Max: 15
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
