---
services:

  analytics_dashboard:
    git_url: git@github.com:learningtapestry/analytics-dashboard.git
    git_branch: master
    command: npm start
    build_root: .
    ports:
      - container: 3000
        http: 80
        https: 443
    env_vars:
      NODE_ENV: production
